### ISSUE TITLE
Scenario synchronization issues in Sand World

### ISSUE THREAD

**Issue by unuruu5760** [CraftyBoss/SuperMarioOdysseyOnline#33]
There is an issue in Sandworld where one person cannot open the boss room. 
Only the person who gets the moon here first will open the door to the boss room. The second person can never open the boss room door.
Suicide doesn't solve this. My guess is that it doesn't forward the packet for the condition that the bossroom opens.
![2022-08-17 21 45 11](https://user-images.githubusercontent.com/69958962/185384361-74d06973-6233-43c4-9edb-b1869b9ea918.png)
![2022-08-17 21 40 35](https://user-images.githubusercontent.com/69958962/185384415-a3e323d1-5069-476b-bb1c-a62388a0ccb4.png)

**Comment by Crazalu** [comment]
...how did this happen? I mean this should be fixed if someone gets the multimoon at IP but this can only occur if you were in a subarea when the shards moon was grabbed.

**Comment by unuruu5760** [comment]
> ...how did this happen? I mean this should be fixed if someone gets the multimoon at IP but this can only occur if you were in a subarea when the shards moon was grabbed.

If two people are in the same place and one person grabs the moon, the boss door will open and the moon will sync with the other person, but that person boss door will not open. Try this yourself and you'll see what I mean.

**Comment by speyejack** [comment]
Was this tried with the server scenario sync setting enabled? If so, has this been tested on the latest dev build?

**Comment by speyejack** [comment]
If this is reproduced, please leave a comment and ill open this again.

**Comment by unuruu5760** [comment]
> If this is reproduced, please leave a comment and ill open this again.

https://www.youtube.com/watch?v=S1ezc728amg

It still can't open the boss room door. I have a test video of this. The latest version of SMO ONLINE developer was used(20230904_013916_SMO_Online_for_Emulators.zip
), and the server used Sanae6 version 1.0.3.

server setting
{
  "Server": {
    "Address": "0.0.0.0",
    "Port": 1027,
    "MaxPlayers": 8
  },
  "Flip": {
    "Enabled": true,
    "Players": [],
    "Pov": "both"
  },
  "Scenario": {
    "MergeEnabled": true
  },
  "BanList": {
    "Enabled": false,
    "Players": [],
    "IpAddresses": []
  },
  "Discord": {
    "Token": null,
    "Prefix": "$",
    "CommandChannel": null,
    "LogChannel": null
  },
  "Shines": {
    "Enabled": true
  },
  "PersistShines": {
    "Enabled": false,
    "Filename": "./moons.json"
  }
}

**Comment by Istador** [comment]
> Was this tried with the server scenario sync setting enabled? If so, has this been tested on the latest dev build?

Collecting shine `496` (Moon Shards in the Sand) does not change the scenario but stays in scenario 1.

Also: the scenario sync setting only affects that the scenario of other players is faked to be equal with your own, it does not send you into another scenario.

Likely the condition for the door to be open or not is not linked to the moon being collected or not but saved separately by the game (e.g. story progression?).

**Comment by speyejack** [comment]
It seems like the pyramid itself has a lot of hard coded values in it and needs to be handled in an entirely different way. So I dont think this particular one will be fixed since it is so specialized. I appreciate the video and the diagnostics though!
